/*
 * hiusbc_reg.h -- Register List for Hisilicon USB Controller.
 *
 * Copyright (c) 2019 Hisilicon Technologies CO., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#ifndef __HIUSBC_REG_H
#define __HIUSBC_REG_H

#define COM_BASE_ADDR 0x10000
#define DRD_MODE_OFFSET 0x4
#define DRD_WORK_MODE_MASK 0x1
#define DRD_WORK_MODE_SHIFT 0
#define CSR_RST_N_OFFSET 0x8
#define TRPU_COM_RSV_OFFSET 0x18
#define U3_CONTINUE_MODE_OFFSET 0x600
#define USBC_U3_EN_MASK 0x4
#define USBC_U2_EN_MASK 0x2
#define U3_CONTINUE_MODE_MASK 0x1
#define U2_VBUS_SEL_OFFSET 0x618
#define U2_VBUS_SEL_MASK 0x3
#define U2_VBUS_SEL_SHIFT 0
#define U3_VBUS_SEL_OFFSET 0x61C
#define U3_VBUS_SEL_MASK 0x1
#define U3_VBUS_SEL_SHIFT 0
#define U2_VBUS_FCE_EN_OFFSET 0x620
#define U2_VBUS_FCE_EN_MASK 0x1
#define U3_VBUS_FCE_EN_OFFSET 0x624
#define U3_VBUS_FCE_EN_MASK 0x1
#define PHY_SEL_MODE_OFFSET 0x628
#define PHY_SEL_MODE_MASK 0x3
#define PHY_SEL_MODE_SHIFT 0
#define VBUS_SEL_MODE_OFFSET 0x634
#define VBUS_SEL_MODE_MASK 0x1
#define VBUS_SEL_MODE_SHIFT 0
#define GLOBAL_TIMESTAMP_OFFSET 0x680
#define BI_CNT_MASK 0xFFFFE000
#define BI_CNT_SHIFT 13
#define PHY_DONE_STATUS_OFFSET 0x71C

#define DEV_BASE_ADDR 0x8000
#define DEV_USB3_U1EL_OFFSET 0x0
#define DEV_USB3_U1PEL_SHIFT 16

#define DEV_USB3_U2EL_OFFSET 0x4
#define DEV_USB3_U2PEL_SHIFT 16

#define DEV_CMD_CTRL_OFFSET 0x8
#define DEV_CMD_DONE_INFO_MASK 0xF000
#define DEV_CMD_DONE_INFO_SHIFT 12
#define DEV_CMD_DONE_MASK 0x100
#define DEV_CMD_VLD_MASK 0x1

#define DEV_CMD_WORD0_OFFSET 0xC

#define DEV_CMD_WORD1_OFFSET 0x10

#define DEV_CMD_WORD2_OFFSET 0x14

#define DEV_CMD_WORD3_OFFSET 0x18

#define DEV_CFG_OFFSET 0x1C
#define DEV_EWE_MASK 0x2
#define LPM_ENABLE_MASK 0x1

#define DEV_CTL_OFFSET 0x20
#define DSEE_MASK 0x40000
#define ENABLE_U2_ACCEPT_MASK 0x20000
#define ENABLE_U1_ACCEPT_MASK 0x10000
#define ENABLE_U2_INITIATE_MASK 0x8000
#define ENABLE_U1_INITIATE_MASK 0x4000
#define BESL_THRESHOLD_SUSPEND_MASK 0x3C00
#define BESL_THRESHOLD_SUSPEND_SHIFT 10
#define DEV_RUN_STOP_MASK 0x1

#define DEV_RST_OFFSET 0x24
#define DEV_RST_MASK 0x1

#define DEV_STATUS_OFFSET 0x2C
#define DEV_EVENT_INTERRUPT_MASK 0x10
#define DCHALTED_MASK 0x2

#define DEV_EVENT_EN_OFFSET 0x30
#define VENDOR_TEST_EVENT_EN_MASK 0x40000
#define L1_RESUME_EVENT_EN_MASK 0x80
#define L1_ENTRY_EVENT_EN_MASK 0x40
#define U3_RESUME_EVENT_EN_MASK 0x20
#define SUSPEND_ENTRY_EVENT_EN_MASK 0x10
#define USB_RESET_EVENT_EN_MASK 0x4
#define CONNECT_EVENT_EN_MASK 0x2
#define DISCONNECT_EVENT_EN_MASK 0x1

#define DEV_EVENT_OFFSET 0x38

#define DEV_U2_PORTSC_OFFSET 0x80
#define DEV_U2_LWS_MASK 0x100
#define DEV_U2_PORT_SPEED_MASK 0xF0
#define DEV_U2_PORT_SPEED_SHIFT 4
#define DEV_U2_PLS_MASK 0xF
#define DEV_U2_PLS_SHIFT 0

#define DEV_U3_PORTSC_OFFSET 0x84
#define DEV_U3_LWS_MASK 0x1000
#define DEV_U3_PORT_SPEED_MASK 0xF00
#define DEV_U3_PORT_SPEED_SHIFT 8
#define DEV_U3_PLS_MASK 0x78
#define DEV_U3_PLS_SHIFT 3

#define DEV_U2PORT_TEST_MODE_OFFSET 0x88
#define DEV_TEST_MODE_MASK 0xF
#define DEV_TEST_MODE_SHIFT 0

#define DEV_U3_UX_EXIT_CFG_OFFSET 0x98
#define DEV_UX_EXIT_INTERVAL_MASK 0xFF0
#define DEV_UX_EXIT_INTERVAL_SHIFT 4
#define DEV_U3_ISOCH_DELAY_OFFSET 0x9C
#define DEV_ISOCH_DELAY_MASK 0xFFFF
#define TRPU_DEV_USB_CTRL_OFFSET 0x100
#define TRPU_DEV_U2_LP_MOD_MASK 0x400
#define DEV_IMAN_0_OFFSET 0x200
#define DEV_INT_ENABLE_0_MASK 0x2
#define DEV_INT_PENDING_0_MASK 0x1
#define DEV_IMOD_0_OFFSET 0x204
#define DEV_INT_MOD_INTERVAL_0_MASK 0xFFFF
#define DEV_INT_MOD_INTERVAL_0_SHIFT 0
#define DEV_EBSZ_0_OFFSET 0x208
#define DEV_EBBA0_0_OFFSET 0x210
#define DEV_EBBA1_0_OFFSET 0x214
#define DEV_EBDP0_0_OFFSET 0x218
#define DEV_EVENT_HANDLER_BUSY_0_MASK 0x8
#define DEV_EBDP1_0_OFFSET 0x21C

#define HOST_BASE_ADDR 0x0
#define TRPU_HOST_DB_ITVL_OFFSET 0x3010
#define TRPU_HOST_CTRL_MODE_OFFSET 0x3018
#define TRPU_HOST_BLOCK_MODE_MASK 0x1
#define TRPU_HOST_SEP_MBS_OFFSET 0x3028
#define FS_MS_PBYTE_NUM_OFFSET 0x4014

#define LMI_BASE_ADDR 0x17000
#define LMI_AXI_AWLEN_CFG_OFFSET 0x0
#define CSR_LMI_LEN_CTRL_MASK 0xF

#define LMI_AXI_QOS_MAP_CFG_OFFSET 0x4

#define LMI_AXI_CACHE_CFG_OFFSET 0x8

#define U2PM_BASE_ADDR 0x28000
#define CSR_DEV_PRTRST_HS_HANDSHAKE_EN_OFFSET 0xA14
#define CSR_DEV_PRTRST_HS_HANDSHAKE_EN_MASK 0x1
#define U3LINK_BASE_ADDR 0x38000
#define CSR_TARGET_SPEED_OFFSET 0x130
#define CSR_TARGET_SPEED_MASK 0x3
#define CSR_TARGET_SPEED_SHIFT 0
#define CSR_CP_PAT_SEL_OFFSET 0x26C
#define CSR_CP_PAT_SEL_MASK 0x1

#define CSR_CP_PAT_OFFSET 0x270
#define CSR_CP_PAT_MASK 0x1F

#define CSR_CP_PAT_SW_CTRL_OFFSET 0x274
#define CSR_CP_PAT_SW_CTRL_MASK 0x1

#define CSR_CP_PAT_SW_OFFSET 0x278
#define CSR_CP_PAT_SW_MASK 0x1
#define CSR_DFX_STATE_CFG_OFFSET 0x500
#define CSR_DFX_STATE_CLR_MASK 0x2
#define CSR_DFX_STATE_WR_EN_MASK 0x1

#define CSR_STATE_DFX_REG0_OFFSET 0x504

#define HUB_BASE_ADDR 0x14000
#define CUR_LOC_STATUS_OFFSET 0x124
#define CUR_CLK_PIPE_LOC_MASK 0x2
#define CUR_CLK_U2PHY_LOC_MASK 0x1

#define FREQ_EXAM_EN_OFFSET 0x12C
#define CLK_PIPE_EXAM_EN_MASK 0x2
#define CLK_U2PHY_EXAM_EN_MASK 0x1

#define FREQ_EXAM_COUNTER_OFFSET 0x130
#define CLK_PIPE_FREQ_EXAM_COUNTER_MASK 0xFFFF0000
#define CLK_PIPE_FREQ_EXAM_COUNTER_SHIFT 16
#define CLK_U2PHY_FREQ_EXAM_COUNTER_MASK 0xFFFF

#define FREQ_EXAM_DONE_OFFSET 0x134
#define CLK_PIPE_FREQ_EXAM_DONE_MASK 0x2
#define CLK_U2PHY_FREQ_EXAM_DONE_MASK 0x1

#define USBC_SOFT_RST_OFFSET 0x138
#define RST_SOFT_TRPU_HOST_N_MASK 0x2
#define RST_SOFT_TRPU_HOST_N_SHIFT 1
#define RST_SOFT_TRPU_DEV_N_MASK 0x1
#define RST_SOFT_TRPU_DEV_N_SHIFT 0
#endif /* __HIUSBC_REG_H */
